### ISSUE TITLE
Is it possible to create a new thread under given channel of Microsoft Teams through any programming language?

### ISSUE THREAD

**Issue by sai78** [OfficeDev/office-js-helpers#111]
Hello Team,

I want to create a new thread under given channel in Microsoft Teams using Node JS. Is it possible? If yes please suggest me the corresponding documentation.

Thanks in advance.

**Comment by LouMM** [comment]
Thank you @sai78 for your questions about Microsoft Teams. Unfortunately this repo is more for Office Addins that use Office.js as they API pipeline. Don't fret it though! There are several places for you to ask a question about this topic.

- **General questions**: Please send email to [Microsoft Teams developer support.](microsoftteamsdev@microsoft.com)
- **Programming questions:** The team listens and responds on [Stack Overflow](http://stackoverflow.com/questions/tagged/microsoft-teams). Follow the [guidance ](http://stackoverflow.com/tour)about what makes a good question on Stack Overflow. Tag your question with microsoft-teams so that our team and the Microsoft Teams developer community can spot your question.
