### ISSUE TITLE
Please add npm script to run tests

### ISSUE THREAD

**Issue by darcyparker** [OfficeDev/office-js-helpers#14]
How do you run your tests? I did not find `npm run test`.

On a related note, `typings` is required for `npm run build`.  I see you install it for travis...  I suspect it was an oversight to not including installing typings with `npm install`.  I can see why you wouldn't put it in definition for `npm run build` because you don't need to keep installing typings.  I suspect you want to add:
`"postinstall": "npm run typings install"` to the scripts section of your package.json?

**Comment by WrathOfZombies** [comment]
Well there's a problem. Assuming you used @types in your codebase, you'd end up with conflicting types as the postinstall script is even run for dependencies. 

So I found it's better to install it manually instead of automating that process. 

On the testing front, I have intentionally left it out as I am still in the process of adding features/writing tests. Besides I plan to switch to mocha instead just cause it plays nicely with karma. Will update the scripts when the tests are in place. Also there's no way to mock the Office.js APIs for Dialogs so, thats another blocker.

**Comment by darcyparker** [comment]
@WrathOfZombies - thanks for explanation.

**Comment by WrathOfZombies** [comment]
@darcyparker. Seems like there's a better alternative. I am testing out the use of @types by default instead of depending on typings altogether. That should help at least with the second part of the problem.
