### ISSUE TITLE
 Unable to get property 'registerForEvent' of undefined or null reference

### ISSUE THREAD

**Issue by EliseoAzpeitia** [OfficeDev/office-js-helpers#29]
When I use OfficeHelpers.Authenticator.isAuthDialog() throw this error and IE doesn't close de dialog
Example:
Office.initialize = function (){

			if (OfficeHelpers.Authenticator.isAuthDialog()) return;
			var authenticator = new OfficeHelpers.Authenticator();
			 authenticator.endpoints.add("endpoint", {
				baseUrl: "BASE_URL",
				authorizeUrl: "Authorize_URL",
				clientId: "Client_id",
				responseType: "token",
				scope: "user",
				redirectUrl: "redirect",
			});

			var t = authenticator.authenticate("endpoint");
			t.then(function(token){
	
				console.log("logged");
			})
			.catch(function(error){

				console.log(error);
			})
		}

**Comment by WrathOfZombies** [comment]
Well I don't recall using `registerForEvent` anywhere. Could you paste the stack trace completely so that we can see what's the root cause?

Also I am assuming that you have included OfficeJS and you are not seeing any network errors which loading the OfficeJS dependencies and you are trying this from inside of an Add-in.

**Comment by antifun** [comment]
I'm also having this problem. 
```

**Comment by antifun** [comment]
For anyone else who stumbles across this, it turns out that most of my problems were caused by a lack of `AppDomains` matching the domain for opened authentication dialogs. The particulars of the add-in API and browser origin restrictions mean that (correct me if I'm wrong):

* You pop open a dialog under some domain listed in AppDomains
* That needs to redirect you to your actual oauth provider
* The redirect_uri at the provider needs to point back at a URL in an AppDomain
* That URL needs to understand what to do with the `access_token` etc. from the response.

This helper is built to accomplish those tasks for you, and it works, *if* you have the AppDomains set up properly; if not, you'll get odd errors from the browser like the ones I noted above.

Important tip: you have to *reload* the manifest if it's been loaded from the filesystem by removing and re-adding the add-in! This was what I had failed to do, and it cost me several days of hand-wringing and head-desking to figure out.

**Comment by WrathOfZombies** [comment]
@Zlatkovsky would you be open to writing a blog post about this on OfficeDev?

**Comment by Zlatkovsky** [comment]
Let me hand it off to our documentation team or PMs.  I'll send an internal email about it.

**Comment by Zlatkovsky** [comment]
Assigning to @Reezaali , I'll talk with him in person offline.

**Comment by Reezaali** [comment]
Wouldn't it be better to write out an error message that suggests someone review their AppDomains settings when you catch the error? Writing a blog post won't be an effective way to solve this problem. Thanks!
