### ISSUE TITLE
OfficeHelpers.Utilities.host incorrectly identifies Word Office 2013 in Win 7 as "WEB"

### ISSUE THREAD

**Issue by LucasMoffitt** [OfficeDev/office-js-helpers#36]
OfficeHelpers.Utilities.host will return "WEB" while running in Office 2013 on Windows 7.

I believe (but haven't verified) that it's catching an error as below.

```
catch (error) {
        return { host: 'WEB', platform: null };
    }
```

**Comment by WrathOfZombies** [comment]
@Zlatkovsky something that you'd be better at resolving.

My hunch is the sessionStorage object either being null due to Office.js not being available or due to it not having the right values. 

@LucasMoffitt can you patch your local copy of OfficeHelpers to do a `OfficeHelpers.Utilities.log(error)` just before the return so that it can help us identify the issue.

**Comment by Zlatkovsky** [comment]
@LucasMoffitt , where are you calling this from?  The code is only guaranteed to return correct values if it's run inside of or after `Office.initialized` has been called.

**Comment by WrathOfZombies** [comment]
Probably related to #38
