### ISSUE TITLE
Unhandled exception in https://localhost:*****/office.helpers.min.js 0x800a1391 - JavaScript runtime error: 'Promise' is undefined occurred

### ISSUE THREAD

**Issue by cognologixguru** [OfficeDev/office-js-helpers#43]
Hi,
I have done following code in Home.js. It returns following exception.

Unhandled exception at line 1, column 1149 in https://localhost:44365/office.helpers.min.js
0x800a1391 - JavaScript runtime error: 'Promise' is undefined occurred

[sample.zip](https://github.com/OfficeDev/office-js-helpers/files/1260274/sample.zip)

Solution : Add following code before OfficeJSHelper.js

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js" class="pre"></script>

**Comment by WrathOfZombies** [comment]
Can you try with `core-js`?

**Comment by cognologixguru** [comment]
I have not tried it "Core-js" but "bluebird.min.js" is preferred solution for "Promise" issue.

**Comment by WrathOfZombies** [comment]
As long as your browser has a standard `Promise` it should be fine. 

If not you would need standard polyfills that defines window.Promise. I see a lot of community support for `core-js` and hence the recommendation.

Also I am aware of bluebird and I am not sure where the preferred recommendation comes from. Could you point me to some docs so that I can understand why? I am finding it surprisingly difficult to confirm that a standard build of bluebird.js overrides `window.Promise`. All I see are examples which do es6 import.

```javascript
import * as Promise from 'bluebird';
```
